# -*- coding: utf-8 -*-
"""Copy of AT_CapstoneProject1_DiceRollGame_QuestionCopy_v0.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcwSTV4CVpjadSVRS_9-NZsKX4o_G-MN

# Capstone Project 1: Dice Roll Game

---

### Overview

In this project, you have to create a Dice Roll game in which two players will roll the dice one after another for 10 rounds. In each round, if the number on dice face for player 1 is greater than that for player 2, player 1 scores a point else player 2 will score a point. After 10 rounds, the player having the highest score is declared as the winner.

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/14VKG4f02U87t8truYCPmX_QSUM_zF92n

2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_CapstoneProject1** format.

3. Now, write your code in the prescribed code cells.

---

### The Algorithm

In the algorithm, two players will compete with each other by rolling the die one after another.<br/>
- One turn each from both players is called a round.<br/>
- After each round one of the player will be declared as winner of the said round as they progress to the next.
- 10 rounds will be played in a similar fashion.
- After round 10, the player with more round wins will be declared as the winner of the game.


**The output should look like this:**

```
Round:  1
Player 1 Roll:  2
Player 2 Roll:  4
Player 2 wins!
Round:  2
Player 1 Roll:  1
Player 2 Roll:  3
Player 2 wins!
...
...
Round:  10
Player 1 Roll:  5
Player 2 Roll:  4
Player 1 wins!
Final Winner: Player 1- Rounds Won:  6
```

**Note:** The game is not accepting any user input. So no need of using `input()` function.

___

#### Import the `random` Module and Create the required variables

- Import the `random` module.
"""

# Import the random module in the next line.
import random

"""___

#### Create the `dice_roll()` Function

Next, create a function called `dice_roll()`. Inside this function,
- Generate a random integer between 1 to 6 using `randint()` function and store this in a variable `dice_roll`
- Return this variable.
"""

# Create the dice_roll() function.
def dice_roll():
    dice_roll = random.randint(1, 6)
    return dice_roll

"""___

#### Create the `main()` Function

Now, create a function `main()` and perform the following tasks inside this function:

1. Create the `player1`, `player1_score`, `player2` and `player2_score` variables and set their initial values equal to `0`. Create a `rounds` variable and assign the value of `1` to it.
2. Create a `while` loop which runs unless `rounds` equal to `10` i.e., till `rounds != 11`. Inside the `while` loop, perform the following tasks:
  - Print current round using `print()` function, passing the `"Rounds "` string as well as `rounds` variable.
  - Call `dice_roll()` function for Player 1 and Player 2 and store the return value in `player1` and `player2` variables respectively.
  - Print the value of `player1` and `player2` variables.
  - Using `if-else` statement, compare the values of `player1` and `player2` variables.
     - If `player1 == player2`, print `Draw!`.
     - Else if `player1 > player2`, increase the value of `player1_score` variable by `1` and print `Player 1 wins!`.
     - Else increase `player2_score` by `1` and print `Player 2 wins!`.
 - Increase `rounds` variable value by `1`.

3. Outside the `while` loop, compare the score of both the players obtained after 10 rounds by comparing the values of the variables `player1_score` and `player2_score`.

  - If `player1_score == player2_score` then print `Draw!`.
  - Else if `player1_score > player2_score` then print:
  
    `"Final Winner: Player 1 - Rounds Won: ", player1_score`
  
  where `player1_score` contains the number of rounds won by player1.
  
  - Else print:
    
    `"Final Winner: Player 2 - Rounds Won: ", player2_score`
  
   where `player2_score` contains the number of rounds won by player2.
"""

import random

def dice_roll():
    #Generate a random number between 1 and 6 and return the result
    return random.randint(1, 6)

def main():
    rounds = 1
    player1_score = 0
    player2_score = 0

    # Create a while loop which runs till rounds != 11
    while rounds != 11:
        # print current round number using print() function as print("Round: ", rounds)
        print("Round: ", rounds)

        # Call dice_roll() function for Player 1 and Player 2 and store the return value in player1 and player2 respectively.
        player1 = dice_roll()
        player2 = dice_roll()

        # print the outcomes of Player 1 & 2
        print("Player 1 rolls: ", player1)
        print("Player 2 rolls: ", player2)

        # Check if, player1 value equals that of player2. If it does, print Draw!.
        if player1 == player2:
            print("Draw!")

        # check if player1 is greater than player2. If yes, increase player1_score by 1 and print Player 1 wins!
        elif player1 > player2:
            player1_score += 1
            print("Player 1 wins!")

        # else increase player2_score by 1 and print Player 2 wins!.
        else:
            player2_score += 1
            print("Player 2 wins!")

        # Increse rounds by 1.
        rounds += 1

    # Outside while loop check if, player1_score value equals that of player2_score, print Draw!
    if player1_score == player2_score:
        print("Draw!")

    # check whether player1_score is greater than player2_score.
    # If yes, print("Final Winner: Player 1- Rounds Won: ", player1_score)
    elif player1_score > player2_score:
        print("Final Winner: Player 1 - Rounds Won: ", player1_score)

    # Otherwise print("Final Winner: Player 2 - Rounds Won: ", player2_score)
    else:
        print("Final Winner: Player 2 - Rounds Won: ", player2_score)

if __name__ == "__main__":
    main()

"""___

#### Call the `main()` function
"""

# Call the 'main()' function
main()

"""---

### How To Submit The Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_CapstoneProject1**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_CapstoneProject1** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""